#pragma config(Sensor, S2,     sound,          sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
true && true = true
false && false = false
false && true = false
true && false = false
*/

int Time = 0;
int Clap = 50;

void display()
{
    displayMotorValues(line4, motorC);
    displayMotorValues(line3, motorB);
    displaySensorValues(line6, sound);
    nxtDisplayTextLine(line1,"2.2f",Time);
}

task main()
{
    display();
    playSound(soundFastUpwardTones);
    motor[motorB] = 50;
    motor[motorC] = 50;
    wait1Msec(0500);
    
    motor[motorB] = 100;
    motor[motorC] = 100;
    wait1Msec(0500);
    
    while (true)
    {
        while (Time == 0)
        {  
            wait1Msec(0150);
            motor[motorB] = 0;
            motor[motorC] = 0;
            display();
            
            if (SensorValue[sound] > Clap)
            {
                Time = 1;
            }
        }
        while (Time == 1)
        {
            wait1Msec(0150);
            motor[motorB] = 50;
            motor[motorC] = 50;
            display();
            
            if (SensorValue[sound] > Clap + 20)
            {  
                Time = 2;
            }
        }
        while (Time == 2)
        {
            wait1Msec(0150);
            motor[motorB] = 100;
            motor[motorC] = 100;
            display();
            
            if (SensorValue[sound] > Clap + 40)
            {
                Time = 0;
            }
        }
    }
}