#pragma config(Sensor, S2,     light,                  sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 true && true = true
 false && false = false
 false && true = false
 true && false = false
*/

task main()
{
    float offset; //Threshold
    float Kp = 7; //Proportional
    float Ki = 0.00018; //Integral
    float Kd = 0.00018; //Derivative
    float Tp = 40; //Turn Power
    float error; //When light != offset
    float integral; //I
    float derivative; //D
    float lastError; //Try to get error to always equal 0
    float turn; //Amount of turning power
    float powerB;
    float powerC;
    int tooLow; //When on line...
    int tooHigh; //When off line...
    
    //Calibrating the value of the threshold (offset)
    //Robot needs to be placed on line
    wait1Msec(1000);
    PlaySound(soundBlip);
    tooLow = SensorValue(light); //When on line
    wait1Msec(0500);
    
    //auto calibration
    motor[motorB] = 75;
    wait1Msec(1000);
    PlaySound(soundBeep);
    //auto calibration done
    
    wait1Msec(0500)
    tooHigh = SensorValue(light); //When off line
    PlaySound(soundBlip);
    offset = (tooLow+tooHigh)/2; //Calculates threshold
    
    while(true)
    {
        error = SensorValue(light)-offset; //On a straight line this will be a small number, when turning it will become a bigger number
        integral = integral+error;
        derivative = error-lastError;
        turn = (Kp*error)+(Ki*integral)+(Kd*derivative); //If error = 3, then turn = around 21
        powerB = Tp-turn; //Adjust to line
        powerC = Tp+turn; //Adjust to line
        motor[motorB] = powerB;
        motor[motorC] = powerC;
        lastError = error; //Try to get error to always equal 0
    }
}
